version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(rust)"
    open-pull-requests-limit: 99
    labels:
      - "dependencies"
      - "rust"
    groups:
      production-dependencies:
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
          - "major"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(actions)"
    open-pull-requests-limit: 99
    labels:
      - "dependencies"
      - "ci"
    groups:
      actions:
        patterns:
          - "*"

  # Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "deps(docker)"
    open-pull-requests-limit: 99
    labels:
      - "dependencies"
      - "docker"
