//! Init command implementation - config file generator.

use std::path::Path;

use anyhow::Result;

use super::common::{colors, cprintln};

/// Parameters for the init command.
#[derive(Debug)]
pub struct InitParams {
    pub output: String,
    pub node_id: u64,
    pub listen_addr: String,
    pub raft_addr: String,
    pub metrics_addr: String,
    pub pg_data_dir: String,
    pub pg_bin_dir: Option<String>,
    pub force: bool,
}

/// Run the init command - generate a starter configuration file.
///
/// # Errors
/// Returns an error if the file exists without `--force`, addresses are
/// invalid, the `PostgreSQL` binary dir can't be detected, or the write fails.
pub async fn run_init(params: InitParams) -> Result<()> {
    use colors::{BOLD, DIM, GREEN, RESET};

    let InitParams {
        output,
        node_id,
        listen_addr,
        raft_addr,
        metrics_addr,
        pg_data_dir,
        pg_bin_dir,
        force,
    } = params;

    // 0 is the join-time auto-assign sentinel; a config generated with it
    // would bootstrap a cluster whose leader id reads as "unset" to every
    // tool (`cluster remove --self`, join's resume path).
    if node_id == 0 {
        anyhow::bail!("--node-id 0 is reserved (join-time auto-assign sentinel); node IDs start at 1");
    }

    let output_path = Path::new(&output);

    // `write_config_atomic` re-checks existence; failing here as well avoids
    // running pg_bin_dir detection before reporting the obvious error.
    if !force && output_path.exists() {
        anyhow::bail!("Config file '{output}' already exists. Use --force to overwrite.");
    }

    // Auto-detect pg_bin_dir if not specified
    let pg_bin = match pg_bin_dir {
        Some(dir) => dir,
        None => detect_pg_bin_dir()?,
    };

    // Validate addresses
    listen_addr
        .parse::<std::net::SocketAddr>()
        .map_err(|_| anyhow::anyhow!("Invalid listen_addr: {listen_addr}"))?;
    raft_addr
        .parse::<std::net::SocketAddr>()
        .map_err(|_| anyhow::anyhow!("Invalid raft_addr: {raft_addr}"))?;
    metrics_addr
        .parse::<std::net::SocketAddr>()
        .map_err(|_| anyhow::anyhow!("Invalid metrics_addr: {metrics_addr}"))?;

    // Generate config content
    let config_content = format!(
        r#"# pgbattery configuration
# Generated by: pgbattery init

# Node identifier (unique within cluster)
node_id = {node_id}

# Client connection address (PostgreSQL wire protocol)
listen_addr = "{listen_addr}"

# Raft consensus RPC address
raft_addr = "{raft_addr}"

# Prometheus metrics endpoint
metrics_addr = "{metrics_addr}"

# Management API bind address (loopback by default for safety)
mgmt_addr = "127.0.0.1:9091"

# Optional shared token for protected management API writes.
# Required if mgmt_addr is exposed on a non-loopback interface.
# management_api_token = "set-a-long-random-token"

# PostgreSQL paths
pg_bin_dir = "{pg_bin}"
pg_data_dir = "{pg_data_dir}"

# Authentication mode for PostgreSQL connections
# Options: "scram" (default, secure), "md5" (legacy), "trust" (development only)
pg_auth_mode = "scram"

# Cluster peers (add after bootstrapping first node)
# [[peers]]
# id = 2
# raft_addr = "10.0.0.2:5433"
# pg_addr = "10.0.0.2:5434"
# mgmt_addr = "10.0.0.2:9091"
# metrics_addr = "10.0.0.2:9090"

# Backup configuration (optional)
# [backup]
# enabled = true
# backup_dir = "/var/lib/pgbattery/backups"
# backup_type = "full"
# retention_count = 7
"#
    );

    // Write the config file atomically.
    write_config_atomic(output_path, &config_content, force)?;

    cprintln!("{GREEN}✓ Configuration written to: {output}{RESET}");
    cprintln!();
    cprintln!("{BOLD}Next steps:{RESET}");
    cprintln!("  1. Review and adjust the configuration as needed");
    cprintln!("  2. Ensure pg_data_dir exists: mkdir -p {pg_data_dir}");
    cprintln!("  3. Bootstrap the first node:");
    cprintln!("     {DIM}pgbattery --config {output} run --bootstrap{RESET}");
    cprintln!();
    cprintln!("  To add more nodes to the cluster:");
    cprintln!(
        "     {DIM}pgbattery join --peer <leader-mgmt-addr> --write-config node2.toml{RESET}"
    );
    cprintln!();

    Ok(())
}

/// Write `contents` to `path` atomically: temp file in the same directory
/// (`create_new`, so a symlink racing into the temp slot is refused), fsync,
/// then rename over the target.
///
/// `force` only affects the existence pre-check. The target is never
/// unlinked before the new content is durably on disk, so a crash at any
/// point leaves either the old config or the new one — never neither.
pub(super) fn write_config_atomic(path: &Path, contents: &str, force: bool) -> Result<()> {
    use std::io::Write as _;

    if !force && path.exists() {
        anyhow::bail!(
            "Config file '{}' already exists. Use --force to overwrite.",
            path.display()
        );
    }

    let dir = match path.parent() {
        Some(p) if !p.as_os_str().is_empty() => p,
        _ => Path::new("."),
    };
    let file_name = path
        .file_name()
        .and_then(|n| n.to_str())
        .ok_or_else(|| anyhow::anyhow!("Invalid config path: {}", path.display()))?;
    let tmp_path = dir.join(format!(".{file_name}.tmp.{}", std::process::id()));

    let write = || -> Result<()> {
        let mut file = std::fs::OpenOptions::new()
            .create_new(true)
            .write(true)
            .open(&tmp_path)
            .map_err(|e| {
                anyhow::anyhow!("Failed to create temp file at {}: {e}", tmp_path.display())
            })?;
        file.write_all(contents.as_bytes())
            .map_err(|e| anyhow::anyhow!("Failed to write config: {e}"))?;
        file.sync_all()
            .map_err(|e| anyhow::anyhow!("Failed to fsync config: {e}"))?;
        std::fs::rename(&tmp_path, path).map_err(|e| {
            anyhow::anyhow!("Failed to move config into place at {}: {e}", path.display())
        })?;
        super::common::fsync_dir(dir).ok();
        Ok(())
    };
    write().inspect_err(|_| {
        std::fs::remove_file(&tmp_path).ok();
    })
}

/// Try to detect `PostgreSQL` binary directory (returns error if not found).
fn detect_pg_bin_dir() -> Result<String> {
    detect_pg_bin_dir_silent().ok_or_else(|| {
        anyhow::anyhow!(
            "Could not auto-detect PostgreSQL binary directory. \
             Please specify --pg-bin-dir explicitly."
        )
    })
}

/// Try to detect `PostgreSQL` binary directory (returns None if not found).
pub(super) fn detect_pg_bin_dir_silent() -> Option<String> {
    // Common locations to check
    let candidates = [
        "/usr/lib/postgresql/16/bin",
        "/usr/lib/postgresql/15/bin",
        "/usr/lib/postgresql/14/bin",
        "/usr/pgsql-16/bin",
        "/usr/pgsql-15/bin",
        "/usr/pgsql-14/bin",
        "/opt/homebrew/opt/postgresql@16/bin",
        "/opt/homebrew/opt/postgresql@15/bin",
        "/opt/homebrew/opt/postgresql/bin",
        "/usr/local/pgsql/bin",
        "/usr/bin",
    ];

    for candidate in &candidates {
        let pg_ctl = Path::new(candidate).join("pg_ctl");
        if pg_ctl.exists() {
            return Some(candidate.to_string());
        }
    }

    // Try to find via PATH
    if let Ok(output) = std::process::Command::new("which").arg("pg_ctl").output()
        && output.status.success()
    {
        let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
        if let Some(parent) = Path::new(&path).parent() {
            return Some(parent.display().to_string());
        }
    }

    None
}

/// Parameters for generating a join config file.
#[derive(Clone, Copy)]
pub(super) struct JoinConfigParams<'a> {
    pub output_path: &'a str,
    pub node_id: u64,
    pub listen_addr: &'a str,
    pub raft_addr: &'a str,
    pub metrics_addr: &'a str,
    pub pg_data_dir: &'a str,
    pub pg_bin_dir: &'a str,
    pub peers: &'a [(u64, String, String, String, String)],
}

/// Generate a config file from discovered cluster info.
pub(super) fn generate_join_config(params: JoinConfigParams<'_>) -> Result<()> {
    let JoinConfigParams {
        output_path,
        node_id,
        listen_addr,
        raft_addr,
        metrics_addr,
        pg_data_dir,
        pg_bin_dir,
        peers,
    } = params;
    let mut peers_toml = String::new();
    for (id, raft, pg, mgmt, metrics) in peers {
        {
            use std::fmt::Write;
            let _ = write!(
                peers_toml,
                r#"
[[peers]]
id = {id}
raft_addr = "{raft}"
pg_addr = "{pg}"
mgmt_addr = "{mgmt}"
metrics_addr = "{metrics}"
"#
            );
        }
    }

    let config_content = format!(
        r#"# pgbattery configuration
# Generated by: pgbattery join --write-config

node_id = {node_id}
listen_addr = "{listen_addr}"
raft_addr = "{raft_addr}"
metrics_addr = "{metrics_addr}"
mgmt_addr = "127.0.0.1:9091"

# Optional shared token for protected management API writes.
# Required if mgmt_addr is exposed on a non-loopback interface.
# management_api_token = "set-a-long-random-token"

pg_bin_dir = "{pg_bin_dir}"
pg_data_dir = "{pg_data_dir}"

pg_auth_mode = "scram"
{peers_toml}
"#
    );

    // Called via `pgbattery join --write-config`. Use the same atomic
    // helper; `force = true` mirrors the previous behaviour where this
    // function overwrote unconditionally.
    write_config_atomic(Path::new(output_path), &config_content, true)?;
    Ok(())
}

#[cfg(test)]
#[allow(
    clippy::unwrap_used,
    reason = "test code asserts on known-good values and panics are the failure signal"
)]
mod tests {
    use super::*;

    #[test]
    fn write_config_atomic_creates_and_overwrites() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pgbattery.toml");

        write_config_atomic(&path, "node_id = 1\n", false).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "node_id = 1\n");

        // Without --force an existing target is refused and left untouched.
        let err = write_config_atomic(&path, "node_id = 2\n", false).unwrap_err();
        assert!(err.to_string().contains("already exists"));
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "node_id = 1\n");

        // With --force the content is replaced.
        write_config_atomic(&path, "node_id = 2\n", true).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "node_id = 2\n");
    }

    #[tokio::test]
    async fn init_rejects_node_id_zero() {
        let dir = tempfile::tempdir().unwrap();
        let output = dir.path().join("pgbattery.toml");
        let err = run_init(InitParams {
            output: output.to_string_lossy().into_owned(),
            node_id: 0,
            listen_addr: "0.0.0.0:5432".to_string(),
            raft_addr: "0.0.0.0:5433".to_string(),
            metrics_addr: "0.0.0.0:9090".to_string(),
            pg_data_dir: "/var/lib/postgresql/data".to_string(),
            pg_bin_dir: Some("/usr/lib/postgresql/16/bin".to_string()),
            force: false,
        })
        .await
        .unwrap_err();
        assert!(err.to_string().contains("--node-id 0"));
        assert!(!output.exists());
    }

    #[test]
    fn write_config_atomic_leaves_no_temp_files() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("pgbattery.toml");
        write_config_atomic(&path, "x = 1\n", false).unwrap();

        let names: Vec<String> = std::fs::read_dir(dir.path())
            .unwrap()
            .map(|e| e.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        assert_eq!(names, vec!["pgbattery.toml".to_string()]);
    }
}
